build = "1.0.0"
releasedate = "12 June 2025"
# currently unused
## what to tag new DB builds in Git (build # is appended)
#buildtagprefix = ""
## commit message for new DB build (build # is appended)
#buildcommitmsg = "Data release v"

# where do built datasets and other downloads go?
[artifacts]
basename = "Lape_et_al"
# path relative to deployment root
subdir = "data"
# the secondary .zip file containing all the supplementary datasets
supplementarchive = "{basename}_supp_datasets.zip"
supplementarchivedesc = "All supplementary datasets as Excel <tt>.xlsx</tt> files"

[figures]
infilename = "../supplementary_data/supplementary_info.pdf"
outfilename = "{basename}_supp_figs_and_tables.pdf"
description = "Supplementary figures and tables"

[datasources.ICD]
order = 1
tabname = "ICD"
tooltip = "Results based on ICD10 code from UKB data"
# pathname relative to the 'web' directory
infilename = "../supplementary_data/supplementary_data_8.xlsx"
sheetname = "Results"
outbasefilename = "{basename}_{tabname}_{sheetname}"

[datasources.PHE]
order = 2
tabname = "PHE"
tooltip = "Results based on Phecodes"
infilename = "../supplementary_data/supplementary_data_2.xlsx"
sheetname = "Results"
outbasefilename = "{basename}_{tabname}_{sheetname}"


# > …it is strongly discouraged to break an inline table onto multiples lines.
# > If you find yourself gripped with this desire, it means you should be using
# > standard tables. -- https://toml.io/en/v1.0.0#inline-table
[[datasources.ICD.columns]]
targets = 0
name = "Disease"
title = "Disease"
description = "Disease name"
#width = "25%"

[[datasources.ICD.columns]]
targets = 1
name = "ICD10"
title = "ICD10"
description = "ICD10 3-character code from UKB"
width = "8%"

[[datasources.ICD.columns]]
targets = 2
name = "Pathogen"
title = "Pathogen"
description = "Pathogen abbreviation"
width = "10%"

[[datasources.ICD.columns]]
targets = 3
name = "Pair is Assoc?"
title = "Pair is assoc?"
description = "Boolean indicating whether this pair is considered replicated"
width = "8%"

[[datasources.ICD.columns]]
targets = 4
name = "Std. Lev."
title = "Std. lev."
description = "Standard group this pair is part of [Tier 1, Tier 2, Expected Negative (exp_neg), Unknown (unk)]"
width = "8%"

[[datasources.ICD.columns]]
targets = 5
name = "UKB FDR"
title = "UKB FDR"
description = "Per-disease BH FDR adjusted UKB nominal p-value"
#width = "8%"
type = "num"

[[datasources.ICD.columns]]
targets = 6
name = "TNX FDR"
title = "TNX FDR"
description = "Per-disease BH FDR adjusted TNX nominal p-value"
#width = "8%"
type = "num"

[[datasources.ICD.columns]]
targets = 7
name = "UKB OR"
title = "UKB OR"
description = "Odds ratio for UKB pathogen titer [continuous]"
#width = "5%"
type = "num"

[[datasources.ICD.columns]]
targets = 8
name = "TNX OR"
title = "TNX OR"
description = "Odds ratio for TNX test [categorical]"
#width = "5%"
type = "num"


[[datasources.PHE.columns]]
targets = 0
name = "Disease"
title = "Disease"
description = "Disease name"
#width = "26%"

[[datasources.PHE.columns]]
targets = 1
name = "Phecode"
title = "Phecode"
description = "Code representing Phenome-Wide Association Studies (PheWAS); see doi:10.1038/nbt.2749 and https://phewascatalog.org"
width = "8%"
type = "string"

[[datasources.PHE.columns]]
targets = 2
name = "Pathogen"
title = "Pathogen"
description = "Pathogenic organism abbreviation"
width = "10%"

[[datasources.PHE.columns]]
targets = 3
name = "Pair is Assoc?"
title = "Pair is assoc?"
description = "Boolean indicating whether this pair is considered replicated"
width = "8%"

[[datasources.PHE.columns]]
targets = 4
name = "Std. Lev."
title = "Std. lev."
description = "Standard group this pair is part of [Unknown (unk), Tier 1, Tier 2, Expected Negative (exp_neg)]"
width = "8%"

[[datasources.PHE.columns]]
targets = 5
name = "UKB FDR"
title = "UKB FDR"
description = "Per-disease BH FDR adjusted UKB nominal p-value"
#width = "8%"
type = "num"

[[datasources.PHE.columns]]
targets = 6
name = "TNX FDR"
title = "TNX FDR"
description = "Per-disease BH FDR adjusted TNX nominal p-value"
#width = "8%"
type = "num"

[[datasources.PHE.columns]]
targets = 7
name = "UKB OR"
title = "UKB OR"
description = "Odds ratio for UKB titer [continuous]"
#width = "8%"
type = "num"

[[datasources.PHE.columns]]
targets = 8
name = "TNX OR"
title = "TNX OR"
description = "Odds ratio for TNX association test [categorical]"
#width = "8%"
type = "num"


# for 'order' parameter in the DataTable initializer; applies to both tables
[[ordering]]
name = "Pair is assoc?"
dir = "desc"

[[ordering]]
name = "UKB FDR"
dir = "asc"


# unused for the time being
[organisms]
"BKV" = "https://en.wikipedia.org/wiki/BK_virus"
"C. trachomatis" = "https://en.wikipedia.org/wiki/Chlamydia_trachomatis"
"CMV" = "https://en.wikipedia.org/wiki/Cytomegalovirus"
"EBV" = "https://en.wikipedia.org/wiki/Epstein%E2%80%93Barr_virus"
"HBV" = "https://en.wikipedia.org/wiki/Hepatitis_B_virus"
"HCV" = "https://en.wikipedia.org/wiki/Hepatitis_C_virus"
"HHV-6" = "https://en.wikipedia.org/wiki/Human_herpesvirus_6"
"HHV-7" = "https://en.wikipedia.org/wiki/Human_betaherpesvirus_7"
"HPV-16" = "https://en.wikipedia.org/wiki/Papillomaviridae"
"HPV-18" = "https://en.wikipedia.org/wiki/Papillomaviridae"
"H. pylori" = "https://en.wikipedia.org/wiki/Helicobacter_pylori"
"HSV-1" = "https://en.wikipedia.org/wiki/Human_alphaherpesvirus_1"
"HSV-2" = "https://en.wikipedia.org/wiki/Human_alphaherpesvirus_2"
"HTLV-1" = "https://en.wikipedia.org/wiki/Human_T-lymphotropic_virus_1"
"JCV" = "https://en.wikipedia.org/wiki/Human_polyomavirus_2"
"KSHV" = "https://en.wikipedia.org/wiki/Kaposi%27s_sarcoma-associated_herpesvirus"
"MCV" = "https://en.wikipedia.org/wiki/Merkel_cell_polyomavirus"
"T. gondii" = "https://en.wikipedia.org/wiki/Toxoplasma_gondii"
"VZV" = "https://en.wikipedia.org/wiki/Varicella_zoster_virus"
"HIV" = "https://en.wikipedia.org/wiki/HIV"
