build = "1.0.0"
releasedate = "30 December 2024"
# currently unused
## what to tag new DB builds in Git (build # is appended)
#buildtagprefix = ""
## commit message for new DB build (build # is appended)
#buildcommitmsg = "Data release v"

# where do built datasets and other downloads go?
[artifacts]
basename = "Lape_et_al"
# path relative to deployment root
subdir = "data"
# the basename for the results dataset(s)
resultsarchive = "{basename}_results.zip"
resultsarchivedesc = "Results datasets as Excel <tt>.xlsx</tt> files"
resultstarball = "{basename}_results.tar.gz"
resultstarballdesc = "Results datasets as tab-delimited Unix text files"
# the secondary .zip file containing all the supplemental datasets
supplementarchive = "{basename}_supp_datasets.zip"
supplementarchivedesc = "All supplemental datasets as Excel <tt>.xlsx</tt> files"

[figures]
infilename = "../supplemental_data/supplementary_info.pdf"
outfilename = "{basename}_supp_figs_and_tables.pdf"
description = "Supplemental figures and tables"

[datasources.ICD10]
order = 1
tabname = "ICD10"
tooltip = "Results based on ICD10 code from UKB data"
# pathname relative to the 'web' directory
infilename = "../supplemental_data/supplemental_dataset_2.xlsx"
sheetname = "Results"
outfilename = "{basename}_{tabname}_{sheetname}.xlsx"

[datasources.PHE]
order = 2
tabname = "PHE"
tooltip = "Results based on Phenome-Wide Association Studies (PheWAS)"
infilename = "../supplemental_data/supplemental_dataset_3.xlsx"
sheetname = "Results"
outfilename = "{basename}_{tabname}_{sheetname}.xlsx"


# > …it is strongly discouraged to break an inline table onto multiples lines.
# > If you find yourself gripped with this desire, it means you should be using
# > standard tables. -- https://toml.io/en/v1.0.0#inline-table
[[datasources.ICD10.columns]]
targets = 0
name = "Disease"
title = "Disease"
description = "Disease name"
#width = "25%"

[[datasources.ICD10.columns]]
targets = 1
name = "ICD10"
title = "ICD10"
description = "ICD10 3-character code from UKB"
width = "8%"

[[datasources.ICD10.columns]]
targets = 2
name = "Pathogen"
title = "Pathogen"
description = "Organism abbreviation"
width = "10%"

[[datasources.ICD10.columns]]
targets = 3
name = "Pair is Assoc?"
title = "Pair is assoc?"
description = "Boolean indicating whether this pair is considered replicated"
width = "8%"

[[datasources.ICD10.columns]]
targets = 4
name = "Std. Lev."
title = "Std. lev."
description = "Standard group this pair is part of [Unknown (unk), Tier 1, Tier 2, Expected Negative (exp_neg)]"
width = "8%"

[[datasources.ICD10.columns]]
targets = 5
name = "UKB FDR"
title = "UKB FDR"
description = "Per-disease BH FDR adjusted UKB nominal p-value"
#width = "8%"
type = "num"

[[datasources.ICD10.columns]]
targets = 6
name = "TNX FDR"
title = "TNX FDR"
description = "Per-disease BH FDR adjusted TNX nominal p-value"
#width = "8%"
type = "num"

[[datasources.ICD10.columns]]
targets = 7
name = "UKB OR"
title = "UKB OR"
description = "Odds ratio for UKB titer [continuous]"
#width = "5%"

[[datasources.ICD10.columns]]
targets = 8
name = "TNX_OR"
title = "TNX OR"
description = "Odds ratio for TNX association test [categorical]"
#width = "5%"

#[[datasources.ICD10.columns]]
#targets = 6
#name = "UKB_adj_p"
#title = "UKB adj. p"
#description = "Per-disease BH FDR adjusted UKB nominal p-value"
#width = "8%"
#
#[[datasources.ICD10.columns]]
#targets = 7
#name = "TNX_adj_p"
#title = "TNX adj. p"
#description = "Per-disease BH FDR adjusted TNX nominal p-value"
#width = "10%"
#[[datasources.ICD10.columns]]
#targets = 10
#name = "Replication_Status"
#title = "Replication status"
#description = "The UKB-TNX replication status for this dis-org pair [could_not: UKB sig, not enough TNX data to try replication; did_not_attempt: UKB not sig, so no replication attempted; did_not: UKB sig, TNX not sig; rep: UKB sig, TNX sig]"
#visible = false
#
#[[datasources.ICD10.columns]]
#targets = 11
#name = "UKB_nCase"
#title = "UKB number of cases"
#description = "Number of cases in UKB analysis"
#visible = false
#
#[[datasources.ICD10.columns]]
#targets = 12
#name = "UKB_nControl"
#title = "UKB number of controls"
#description = "Number of controls in UKB analysis"
#visible = false
#
#[[datasources.ICD10.columns]]
#targets = 13
#name = "TNX_nCase"
#title = "TNX number of cases"
#description = "Number of cases in TNX analysis"
#visible = false
#
#[[datasources.ICD10.columns]]
#targets = 14
#name = "TNX_nControl"
#title = "TNX number of controls"
#description = "Number of controls in TNX analysis"
#visible = false


[[datasources.PHE.columns]]
targets = 0
name = "Disease_Description"
title = "Disease"
description = "Disease name"
#width = "26%"

[[datasources.PHE.columns]]
targets = 1
name = "Phecode"
title = "Phecode"
description = "Code representing Phenome-Wide Association Studies (PheWAS); see doi:10.1038/nbt.2749 and https://phewascatalog.org"
width = "8%"
type = "string"

[[datasources.PHE.columns]]
targets = 2
name = "Pathogen"
title = "Pathogen"
description = "Pathogenic organism abbreviation"
width = "10%"

[[datasources.PHE.columns]]
targets = 3
name = "Pair is Assoc?"
title = "Pair is assoc?"
description = "Boolean indicating whether this pair is considered replicated"
width = "8%"

[[datasources.PHE.columns]]
targets = 4
name = "Std. Lev."
title = "Std. lev."
description = "Standard group this pair is part of [Unknown (unk), Tier 1, Tier 2, Expected Negative (exp_neg)]"
width = "8%"

[[datasources.PHE.columns]]
targets = 5
name = "UKB FDR"
title = "UKB FDR"
description = "Per-disease BH FDR adjusted UKB nominal p-value"
#width = "8%"
type = "num"

[[datasources.PHE.columns]]
targets = 6
name = "TNX FDR"
title = "TNX FDR"
description = "Per-disease BH FDR adjusted TNX nominal p-value"
#width = "8%"
type = "num"

[[datasources.PHE.columns]]
targets = 7
name = "UKB OR"
title = "UKB OR"
description = "Odds ratio for UKB titer [continuous]"
#width = "8%"
type = "num"

[[datasources.PHE.columns]]
targets = 8
name = "TNX OR"
title = "TNX OR"
description = "Odds ratio for TNX association test [categorical]"
#width = "8%"
type = "num"


# for 'order' parameter in the DataTable initializer; applies to both tables
[[ordering]]
name = "Pair is Assoc?"
dir = "desc"

[[ordering]]
name = "UKB FDR"
dir = "asc"


# unused for the time being
[organisms]
"BKV" = "https://en.wikipedia.org/wiki/BK_virus"
"C. trachomatis" = "https://en.wikipedia.org/wiki/Chlamydia_trachomatis"
"CMV" = "https://en.wikipedia.org/wiki/Cytomegalovirus"
"EBV" = "https://en.wikipedia.org/wiki/Epstein%E2%80%93Barr_virus"
"HBV" = "https://en.wikipedia.org/wiki/Hepatitis_B_virus"
"HCV" = "https://en.wikipedia.org/wiki/Hepatitis_C_virus"
"HHV-6" = "https://en.wikipedia.org/wiki/Human_herpesvirus_6"
"HHV-7" = "https://en.wikipedia.org/wiki/Human_betaherpesvirus_7"
"HPV-16" = "https://en.wikipedia.org/wiki/Papillomaviridae"
"HPV-18" = "https://en.wikipedia.org/wiki/Papillomaviridae"
"H. pylori" = "https://en.wikipedia.org/wiki/Helicobacter_pylori"
"HSV-1" = "https://en.wikipedia.org/wiki/Human_alphaherpesvirus_1"
"HSV-2" = "https://en.wikipedia.org/wiki/Human_alphaherpesvirus_2"
"HTLV-1" = "https://en.wikipedia.org/wiki/Human_T-lymphotropic_virus_1"
"JCV" = "https://en.wikipedia.org/wiki/Human_polyomavirus_2"
"KSHV" = "https://en.wikipedia.org/wiki/Kaposi%27s_sarcoma-associated_herpesvirus"
"MCV" = "https://en.wikipedia.org/wiki/Merkel_cell_polyomavirus"
"T. gondii" = "https://en.wikipedia.org/wiki/Toxoplasma_gondii"
"VZV" = "https://en.wikipedia.org/wiki/Varicella_zoster_virus"
"HIV" = "https://en.wikipedia.org/wiki/HIV"
