title = "After the Infection: A Survey of Pathogens and Non-communicable Human Disease"
journal = "medRxiv"
year = 2023
url = "https://www.medrxiv.org/content/10.1101/2023.09.14.23295428v1"
author = { given_name="Michael", surname="Lape", email="lapema@mail.uc.edu" }

# whom to contact about the publication (or the data)
contacts = [
  { name="Matthew Weirauch", email="Matthew.Weirauch@cchmc.org" },
  { name="Michael Lape", email="lapema@mail.uc.edu" },
]

[[authors]]
given_name = "Michael"
surname = "Lape"
affiliations = [1, 3, 4]

[[authors]]
given_name = "Daniel"
surname = "Schnell"
affiliations = [3]

[[authors]]
given_name = "Sreeja"
surname = "Parameswaran"
affiliations = [4, 6]

[[authors]]
given_name = "Nathan"
surname = "Salomonis"
affiliations = [1, 2, 3]

[[authors]]
given_name = "Lisa"
mi = "J"
surname =  "Martin"
affiliations = [2, 6]

[[authors]]
given_name = "Brett"
mi = "M"
surname = "Harnett"
affiliations = [1]

[[authors]]
given_name = "Leah"
mi = "C"
surname =  "Kottyan"
email = "Leah.Kottyan@cchmc.org"
affiliations = [2, 4, 6, "*"]

[[authors]]
given_name = "Matthew"
mi = "T"
surname =  "Weirauch"
email = "Matthew.Weirauch@cchmc.org"
affiliations = [2, 3, 4, 5, 6, "*"]

##
## Affiliations corresponding to the IDs above
##
[[affiliations]]
id = 1
name = "Department of Biomedical Informatics, University of Cincinnati College of Medicine, Cincinnati, Ohio, USA"
url = "https://med.uc.edu/depart/bmi/home"

[[affiliations]]
id = 2
name = "Department of Pediatrics, University of Cincinnati College of Medicine, Cincinnati, Ohio, USA"

[[affiliations]]
id = 3
name = "Division of Biomedical Informatics, Cincinnati Children’s Hospital Medical Center, Cincinnati, Ohio, USA"
url = "https://bmi.cchmc.org"

[[affiliations]]
id = 4
name = "Center for Autoimmune Genomics and Etiology, Cincinnati Children’s Hospital Medical Center, Cincinnati, Ohio, USA"
url = "https://www.cincinnatichildrens.org/research/divisions/a/genomics-etiology"

[[affiliations]]
id = 5
name = "Division of Developmental Biology, Cincinnati Children’s Hospital Medical Center, Cincinnati, OH, USA"

[[affiliations]]
id = 6
name = "Division of Human Genetics, Cincinnati Children’s Hospital Medical Center, Cincinnati, OH, USA"

[[affiliations]]
id = "*"
name = "Co-corresponding authors"

[[affiliations]]
id = "#"
name = "Contributed equally"
