title = "After the Infection: A Survey of Pathogens and Non-communicable Human Disease"
# title with a <br> to break it at an aesthetically-pleasing spot
h1 = "After the Infection: A Survey of Pathogens<br> and Non-communicable Human Disease"
shorttitle = "Mike Lape's Pathogen/NCD project"
# used as the last path element in the URL
shortname = "lape2024"
# deploy.<deployto>.urlbase becomes the value of site.urlbase for templates
# see helpers/config.py:load_config()
# FIXME: read from environment
deployto = "local"
# live-reload assets with Live.js; automatically disabled if deployto="prod"
livereload = false
sourceurl = "https://tfinternal.research.cchmc.org/gitlab/mike/pathogen_ncd"
issuesurl = "{sourceurl}/issues"
# version string for the repository (code + web site)
sourcever = "0.1.0"
adminemail = "tftoolsadmin@cchmc.org"
emailsubject = "Pathogenic Organism / NCD web site"
# whether to credit Apaxy mod_autoindex theme in the footer
creditinfooter = false

[meta]
lab = "Weirauch Lab"
labhome = "https://weirauchlab.org"
org = "Cincinnati Children's Hospital Medical Center"
orghome = "https://cincinnatichildrens.org"
generators = ["Vim", "GNU Make", "Invoke", "Python", "Jinja"]
creators = [
  "Michael Lape",
  "Kevin Ernst",
  "Weirauch Transcription Factor Research Laboratory",
  "Center for Autoimmune Genomics and Etiology",
  "Department of Human Genetics",
  "Division of Allergy and Immunology",
  "Cincinnati Children's Hospital Medical Center",
]
keywords = [
    "bioinformatics", "genomics", "research", "paper", "publication", "survey",
    "human", "virus", "gene regulation", "transcription factor", "disease",
    "weirauch lab", "cincinnati children's hospital",
]

# active `deploy` settings get copied to `site.host`, `site.publicurl`, etc.
[deploy.local]
host = "localhost"
# NB: don't forget to update `compose.yml` if you change this
port = 8000
# when deployed, where is this site relative to the web server root?
urlbase = ""
publicurl = "http://{host}:{port}{urlbase}"
deploydir = "local.deploy"

[deploy.dev]
host = "bmitfwebd1"
urlbase = "/pubs/{shortname}"
publicurl = "https://tfwebdev.research.cchmc.org{urlbase}"
deploydir = "/var/www/html{urlbase}"

[deploy.prod]
host = "bmitfwebp1"
urlbase = "/pubs/{shortname}"
publicurl = "https://tf.cchmc.org{urlbase}"
deploydir = "/var/www/html{urlbase}"

[htaccess]
# currently unused, as the site is public
#authname = "Pathogenic Organisms and Non-communicable Diseases - Reviewer Access",
#authuserfile = "/etc/httpd24/htpasswd.pathncd"

# for the `IndexIgnore` directive in data/.htaccess
"indexignores" = ".htaccess header.html footer.html Makefile *.md *.json *.tsv *.xlsx"
